### ISSUE TITLE
update the csv2json function

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/open-government-research-exchange#21]
In the spreadsheet we have multiple columns that shoudl be remapped as arrays to the paper.json

columns are:
~~authors~~
~~innovation~~
~~objective~~
~~sector~~
~~region~~
~~methodology~~
~~tool~~
k updated

**Comment by ghost** [comment]
authors
objective
innovation
methodology

should already all have been being parsed on import this whole time.  are you having problems with these fields?

the other ones, i am about to update

**Comment by ghost** [comment]
f008ea2e32adb2592b0ef998433f2c97629ece9a fixes
