### ISSUE TITLE
Data not being pulled from Spreadsheet in the right format

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/open-government-research-exchange#38]
check this page for weird names - all-categories.html

Things like:
AUSTRALIA-EUROPE
AZERBAIJAN-LIBERIA
MEXICO-CANADA-AUSTRALIA-SPAIN-TURKEY
etc

Probably this is more an issue of data insconsistency. Let's see which is the best approach for this. Probably ask Ani to help with this manual consistency issues in the spreadsheet.

**Comment by ghost** [comment]
<img width="557" alt="screen shot 2016-04-22 at 11 18 43 am" src="https://cloud.githubusercontent.com/assets/1042629/14746101/0608b070-087c-11e6-9ce5-f47b64eb0ea9.png">
<img width="546" alt="screen shot 2016-04-22 at 11 17 41 am" src="https://cloud.githubusercontent.com/assets/1042629/14746102/06193eae-087c-11e6-9ce6-ea36f9970246.png">

it is present both in the json subsets and `papers.json`, so it is coming from the csv conversion like this.

in the spreadsheet, it is a CSV list, 
<img width="314" alt="screen shot 2016-04-22 at 11 22 26 am" src="https://cloud.githubusercontent.com/assets/1042629/14746238/9d0a8df4-087c-11e6-8c0d-e7a7f92f28fa.png">

but  we slugify this field as part of the column mapping, as specified in the gulpfile here:

`'Region'                : { value : 'region', slugify : true },`

so maybe this is not as much a data quality issue, as it is that they want to have multiple values here.  i can add parsing by `,` to the mapping options here, if you'd like, but we just have to be aware this will now be an array so we have to update any templates using it accordingly.

want me to go ahead and parse this field to an array?

**Comment by ghost** [comment]
~~i think there might of been a few fields like this, that we actually wanted to be a parsed field.  could u possibly just give me a quick list of all of these if you know off the top of your head and i will change them all at once?~~

EDIT : this is the same issue as https://github.com/ClaudioMendoncaDesign/open-government-research-exchange/issues/21 , i will do a fix for #21  which should also address this
